#!/bin/bash

get_github_config()
{
	if [[ ! -e ~/.dotfiles ]]; then
		where=$(pwd)
		cd
		git clone https://github.com/geam/42_config .dotfiles
		cd .dotfiles
		git checkout linux
		cd $where
		unset where
	fi
}

get_packages_to_config()
{
	files=$(ls packages)
	unset packages_to_config
	type config > /dev/null 2>&1
	if [[ $? -eq 0 ]]; then
		unset -f config
	fi
	for file in $files; do
		. ./packages/$file
		type config > /dev/null 2>&1
		if [[ $? -eq 0 ]]; then
			packages_to_config=( ${packages_to_config[@]} $files )
			unset -f config
		fi
	done
	echo ${packages_to_config[@]}
}

to_config()
{
	packages=$(get_packages_to_config)
	all="Config all packages"
	PS3="Select what you want to do: "
	while [[ -z $stop ]]; do
		select opt in "$all" ${packages[@]} "Quit"; do
			case $opt in
				"$all")
					to_config_sub "${packages[@]}"
					;;
				"Quit")
					stop="OK"
					;;
				*)
					if [[ -n $opt ]]; then
						to_config_sub "$opt"
					else
						echo "You fail sir"
					fi
					;;
			esac
			break
		done
		echo ""
	done
	unset packages
	unset stop
}

to_config_all()
{
	packages=$(get_packages_to_config)
	to_config_sub "${packages[@]}"
	unset packages
}

to_config_sub()
{
	for file in "${@}"; do
		. ./packages/$file
		type config > /dev/null 2>&1
		if [[ $? -eq 0 ]]; then
			config
		else
			echo "Something odd happened will configuring $file"
		fi
	done
}
